<?php

global $CFG;

require_once($CFG->libdir . '/formslib.php');

class set_picture extends \moodleform {
    const EDITOR_OPTIONS = [
        'changeformat' => 1,
        'noclean' => 0,
        'trusttext' => 0,

        'subdirs' => 0,
        'maxfiles' => EDITOR_UNLIMITED_FILES,
        'accepted_types' => ['.jpg', '.jpeg', '.png']
    ];

    function definition() {
        global $DB, $USER;

        $editoroptions = self::EDITOR_OPTIONS;

        $mform = &$this->_form;

        $mform->addElement('header', 'headertype', 'Кнопка предложить свой проект');

        $mform->addElement('html', '<hr>');
        $mform->addElement('text', 'btnadd_link', 'Ссылка на форму');
        $mform->addElement(
            'filemanager',
            'btnadd_picture',
            "Изображение",
            null,
            [
                'subdirs' => 0,
                'maxfiles' => 1,
                'accepted_types' => ['.jpg', '.jpeg', '.png']
            ]
        );

        $this->add_action_buttons();
    }

    function validation($data, $files) {
        $errors = parent::validation($data, $files); // TODO: Change the autogenerated stub
        return $errors;
    }

}
