<?php

global $CFG;

require_once($CFG->libdir . '/formslib.php');


class set_field_view extends \moodleform
{
    const EDITOR_OPTIONS = [
        'changeformat' => 1,
        'noclean'      => 0,
        'trusttext'    => 0,

        'subdirs' => 0,
        'maxfiles' => EDITOR_UNLIMITED_FILES,
        'accepted_types' => ['.jpg', '.jpeg', '.png']
    ];

    function definition()
    {
        global $DB, $USER;

        $editoroptions = self::EDITOR_OPTIONS;

        $mform = &$this->_form;

        $mform->addElement('header', 'headertype', 'Поля, отображаемые в таблице выпускников');
        $mform->addElement('html', '<p>Порядок полей такой же как и при заполнении профиля. Меняется на <a href="/user/profile/index.php"> странице Поля профиля пользователя</a> </p>');

        $arr = $DB->get_records_sql_menu('SELECT shortname, name FROM mdl_user_info_field ORDER BY sortorder');
        $arr = ['email' => 'Эл. почта', 'city'=>'Город', 'country'=>'Страна'] + $arr;
        $select = $mform->addElement('select', 'alumnifield', 'Поля', $arr, ['style'=> 'height: 500px;']);
        $select->setMultiple(true);


        $this->add_action_buttons();
    }
    function validation($data, $files)
    {
        $errors = parent::validation($data, $files); // TODO: Change the autogenerated stub
        return $errors;
    }

}
