<?php
/**
 * User: densh
 * Date: 28.02.2022
 * Time: 14:27
 */

global $CFG;

require_once($CFG->libdir . '/formslib.php');

class company_item extends \moodleform
{
    const EDITOR_OPTIONS = [
        'changeformat' => 1,
        'noclean'      => 0,
        'trusttext'    => 0,

        'subdirs' => 0,
        'maxfiles' => EDITOR_UNLIMITED_FILES,
        'accepted_types' => ['.jpg', '.jpeg', '.png']
    ];

    function definition()
    {
        global $DB, $USER;

        $editoroptions = self::EDITOR_OPTIONS;

        $mform = &$this->_form;
        $mform->addElement('hidden', 'itemid', 0);
        $mform->setType('itemid', PARAM_INT);
        $mform->addElement('hidden', 'action', 0);
        $mform->setType('action', PARAM_TEXT);
        $mform->addElement('hidden', 'usermodified', $USER->id);
        $mform->setType('usermodified', PARAM_INT);
        $mform->addElement('hidden', 'timemodified', time());
        $mform->setType('timemodified', PARAM_INT);

        $mform->addElement('text', 'name', "Наименование предприятия", array('size' => 300));

        $mform->setType('name', PARAM_TEXT);

        $mform->addElement(
            'filemanager',
            'picture',
            "Логотип предприятия",
            null,
            [
                'subdirs' => 0,
                'maxfiles' => 1,
                'accepted_types' => ['.jpg', '.jpeg', '.png']
            ]
        );

        $mform->addElement('editor', 'paragraph', 'Текстовое описание предприятия (о компании, запрос на сотрудничество, каким опытом готовы делиться)', null, $editoroptions);

        $dataregion = array('Москва'=>'Москва', 'Казань'=>'Казань');
        $mform->addElement('select', 'tagregion', 'Регион', $dataregion);

        $dataindustry = array(1=>'1', 2=>'2');
        $mform->addElement('select', 'tagindustry', 'Отрасль', $dataindustry);

        $datacategory = array('делимся опытом'=>'делимся опытом', 'нужна помощь'=>'нужна помощь', 'предложение'=>'предложение', 'спрос'=>'спрос');
        $mform->addElement('select', 'tagcategory', 'Категория (запросы на нетворкинг)', $datacategory);


        $mform->addElement('textarea', 'sitelink', "Ссылка на официальный сайт, страницы в соцсетях",array('rows' => 3, 'cols' => 65));
        $mform->addElement('textarea', 'contact', "Контактное лицо для связи",array('rows' => 3, 'cols' => 65));

        $this->add_action_buttons();
    }
    function validation($data, $files)
    {
        $errors = parent::validation($data, $files); // TODO: Change the autogenerated stub
        return $errors;
    }

}
