<?php
/**
 * User: densh
 * Date: 28.02.2022
 * Time: 14:27
 */

global $CFG;

require_once($CFG->libdir . '/formslib.php');

class item extends \moodleform
{
    const EDITOR_OPTIONS = [
        'changeformat' => 1,
        'noclean'      => 0,
        'trusttext'    => 0,

        'subdirs' => 0,
        'maxfiles' => EDITOR_UNLIMITED_FILES,
        'accepted_types' => ['.jpg', '.jpeg', '.png']
    ];

    function definition()
    {
        global $DB, $USER;

        $editoroptions = self::EDITOR_OPTIONS;

        $mform = &$this->_form;
        $mform->addElement('hidden', 'itemid', 0);
        $mform->addElement('hidden', 'action', 0);
        $mform->addElement('hidden', 'usermodified', $USER->id);
        $mform->addElement('hidden', 'timemodified', time());

        $mform->addElement('text', 'name', "Заголовок");
        $mform->setType('name', PARAM_TEXT);

        $mform->addElement('editor', 'paragraph', 'Текст статьи', null, $editoroptions);

        $this->add_action_buttons();
    }
    function validation($data, $files)
    {
        $errors = parent::validation($data, $files); // TODO: Change the autogenerated stub
        return $errors;
    }

}
